INSERT INTO GENEROS(NOMBRE) VALUES('Accion');
INSERT INTO GENEROS(NOMBRE) VALUES('Aventura');
INSERT INTO GENEROS(NOMBRE) VALUES('Comedia');
INSERT INTO GENEROS(NOMBRE) VALUES('Drama');
INSERT INTO GENEROS(NOMBRE) VALUES('Fantasia');
INSERT INTO GENEROS(NOMBRE) VALUES('Musical');
INSERT INTO GENEROS(NOMBRE) VALUES('Romance');
INSERT INTO GENEROS(NOMBRE) VALUES('Terror');

INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Tom Cruise', 'https://images.mubicdn.net/images/cast_member/2184/cache-2992-1547409411/image-w856.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES ('Adam Sandler', 'https://cdn.britannica.com/52/243652-050-FEE0A5E4/Actor-Adam-Sandler-2019.jpg');
